// Generated by CoffeeScript 1.6.3
(function() {
  var TweetMocker;

  TweetMocker = (function() {
    function TweetMocker() {}

    TweetMocker.prototype.LINK_PATTERN = /([^\s]+\/\/[^\s]+\.[^\s]+\.[^\s]+)/;

    TweetMocker.prototype.USERNAME_PATTERN = /@[^\s]+/g;

    TweetMocker.prototype.HASHTAG_PATTERN = /#[^\s]+/g;

    TweetMocker.prototype.autolink = function(string) {
      string = this.parseHashTags(string);
      string = this.parseUsernames(string);
      string = this.parseUrls(string);
      return string.substr(0, 159);
    };

    TweetMocker.prototype.parseHashTags = function(string) {
      return string.replace(this.HASHTAG_PATTERN, function(hashtag) {
        return "<a href='#'>" + hashtag + "</a>";
      });
    };

    TweetMocker.prototype.parseUsernames = function(string) {
      return string.replace(this.USERNAME_PATTERN, function(username) {
        return "<a href='#'>" + username + "</a>";
      });
    };

    TweetMocker.prototype.parseLinks = function(string) {
      var maxDomainLength, maxPathLength;
      maxPathLength = 14;
      maxDomainLength = 37;
      return text.replace(this.LINK_PATTERN, function(url) {
        return "<a href='" + url + "'>" + url + "</a>";
      });
    };

    return TweetMocker;

  })();

}).call(this);
